version: '3'

networks:
  app-tier:
    driver: bridge
services:
  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '1111:9000'
      - '1112:9001'
    environment:
      MINIO_ROOT_USER: dima
      MINIO_ROOT_PASSWORD: admindima
  admin:
    container_name: admin
    build:
      context: .
    ports:
      - "1113:8080"
    restart: always