version: '3'

networks:
  app-tier:
    driver: bridge

services:
  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: dima
      MINIO_ROOT_PASSWORD: admindima
      MINIO_STORAGE_DRIVES: "1"
    networks:
      - app-tier
