name: Java CI with Maven

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Build app
        run: |
          mvn clean
          mvn -B package --file pom.xml
      - name: Build with Maven
        run: mvn -B test --file pom.xml
      - name: Run tests
        run: mvn test
      - name: Build Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.secret_name_docker_hub_lower_case }}/spring-boot-for-beginners:latest
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{secrets.secret_name_docker_hub_lower_case}}
          password: ${{secrets.secret_lower_case_token}}
      - name: push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.secret_name_docker_hub_lower_case }}/spring-boot-for-beginners:latest
      - name: Setup known_hosts
        run: |
          mkdir -p $HOME/.ssh
          touch $HOME/.ssh/known_hosts
          ssh-keyscan -H ssh slj.avada-media-dev1.od.ua >> $HOME/.ssh/known_hosts
      - name: Transfer Docker image to remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.remote_server_host }}
          username: ${{ secrets.remote_server_username }}
          password: ${{ secrets.remote_server_ssh_key }}
          port: 22
          script: |
            scp MinionsDD.tar ${{ secrets.remote_server_username }}@${{ secrets.remote_server_host }}:/home/avada/web/slj.avada-media-dev1.od.ua/projects
      - name: SSH to remote server and deploy Docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.remote_server_host }}
          username: ${{ secrets.remote_server_username }}
          password: ${{ secrets.remote_server_ssh_key }}
          port: 22
          script: |
            ssh ${{ secrets.remote_server_username }}@${{ secrets.remote_server_host }} 'docker load -i /home/avada/web/slj.avada-media-dev1.od.ua/projects/MinionsDD.tar'
            ssh ${{ secrets.remote_server_username }}@${{ secrets.remote_server_host }} 'docker run -d -p 8489:8489 --name your-app ${{ secrets.secret_name_docker_hub_lower_case }}/spring-boot-for-beginners:latest'