name: Java CI with Maven

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Build app
        run: |
          mvn clean
          mvn -B package --file pom.xml
      - name: Build with Maven
        run: mvn -B test --file pom.xml
      - name: Run tests
        run: mvn test
      - name: Build Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.secret_name_docker_hub_lower_case }}/spring-boot-for-beginners:latest
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{secrets.secret_name_docker_hub_lower_case}}
          password: ${{secrets.secret_lower_case_token}}
      - name: push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.secret_name_docker_hub_lower_case }}/spring-boot-for-beginners:latest
      - name: Deploy to SSH server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.remote_server_host }}
          username: ${{ secrets.remote_server_username }}
          password: ${{ secrets.remote_server_ssh_key }}
          script: |
            if docker ps -a --format '{{.Names}}' | grep -q '^MinionsDD$'; then
              docker stop slj_prominada_admin_dd_di || true
              docker rm slj_prominada_admin_dd_di || true
            fi
            docker pull ${{ secrets.secret_name_docker_hub_lower_case }}/spring-boot-for-beginners:latest
            docker run -d -p 4403:8080 --name slj_prominada_admin_dd_di --network slj_prominada_network_dd_di ${{ secrets.secret_name_docker_hub_lower_case }}/spring-boot-for-beginners:latest