
name: Java CI with Maven

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          maven-version: '3.8.3'
          cache: maven
      - name: Build with Maven
        run: mvn -B -X package --file pom.xml
      - name: Run tests
        run: mvn test